In [70]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt


In [71]:
data=pd.read_excel(r"D:\IITB\econometrics project\data.xlsx")
data.dropna()
data

c1  c2  c3  c4  c5
0   0   5   4   8   6
1   0   0   4   0   2
2   0   2   0   1   3
3   0   3   0   0   2
4   0   0   8   0   0

In [72]:
data2=pd.read_excel(r"D:\IITB\econometrics project\data2.xlsx")
data2.dropna()
data2

f
0  25
1   5
2   4
3   7
4   6

In [73]:
arr1 = pd.DataFrame(data.head())
arr1=arr1.to_numpy()
print(arr1)

[[0 5 4 8 6]
 [0 0 4 0 2]
 [0 2 0 1 3]
 [0 3 0 0 2]
 [0 0 8 0 0]]


In [74]:
arr2 = pd.DataFrame(data2.head())
arr2=arr2.to_numpy()
print(arr2)

[[25]
 [ 5]
 [ 4]
 [ 7]
 [ 6]]


Finding control rights

In [75]:
T=input("Enter Threshold Value: ")
T=int(T)

In [76]:

indexes=[]
for i in range(0,len(data.columns)):
    indexes.append(i)
og_indexes=indexes.copy()
indexes

    

[0, 1, 2, 3, 4]

In [77]:
def func(a,b):
    cfr=[]
    sum=0
    for i in b:
        if (i in a):
            sum=sum+arr2[i][0]
            for j in a:
                sum=sum+arr1[j][i]
            cfr.append(sum)
        else:
            cfr.append(np.nan)
        sum=0
    return cfr



In [78]:

while(True):
    r=func(indexes,og_indexes)
    temp=indexes.copy()
    for x in r:
        if(x<T):
            y=r.index(x)
            indexes.remove(y)
    if(temp==indexes):
        break


In [79]:
res = [x + 1 for x in indexes]
print('C({}) = {}'.format(T,res))
print(r)

C(16) = [1, 3, 4, 5]
[25, nan, 16, 16, 17]


In [80]:
indexes=og_indexes.copy()

In [81]:
def cct(t,p,q):
    while(True):
        r=func(p,q)
        temp=p.copy()
        for x in r:
            if(x<t):
                y=r.index(x)
                p.remove(y)
        if(temp==p):
            break
    return p



finding critical control threshold for a firm i

In [82]:
i=input("Enter the firm whose cct is to be found: ")
i=int(i)
i=i-1

In [83]:
T=0

indexes+og_indexes.copy()
while(True):
    r=cct(T,indexes,og_indexes)
    if(i in r):
        T=T+1
        indexes=og_indexes.copy()
    else:
        break
print('Critical Control Threshold for firm {} = {}'.format(i+1,T-1))


Critical Control Threshold for firm 2 = 15
