In [42]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [43]:
data=pd.read_excel(r"D:\IITB\econometrics project\tata_grp\data1.xlsx")

data=data.fillna(0)
data

Af-Taab Investment Company Limited  Artson Engineering Ltd.  \
0                                    0                        0   
1                                    0                        0   
2                                    0                        0   
3                                    0                        0   
4                                    0                        0   
..                                 ...                      ...   
56                                   0                        0   
57                                   0                        0   
58                                   0                        0   
59                                   0                        0   
60                                   0                        0   

    Automobile Corpn. Of Goa Ltd.  Automotive Stampings & Assemblies Ltd.  \
0                             0.0                                       0   
1                             0.0                                       0   
2                             0.0                                       0   
3                             0.0                                       0   
4                             0.0                                       0   
..                            ...                                     ...   
56                            0.0                                       0   
57                            0.0                                       0   
58                            0.0                                       0   
59                            0.0                                       0   
60                            0.0                                       0   

    Bamnipal Steel Limited  Benares Hotels Ltd.  Edc Limited  \
0                        0                  0.0            0   
1                        0                  0.0            0   
2                        0                  0.0            0   
3                        0                  0.0            0   
4                        0                  0.0            0   
..                     ...                  ...          ...   
56                       0                  0.0            0   
57                       0                  0.0            0   
58                       0                  0.0            0   
59                       0                  0.0            0   
60                       0                  0.0            0   

    Ewart Investments Limited  Ganpati Industrial Pvt Ltd  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           0                           0   
4                           0                           0   
..                        ...                         ...   
56                          0                           0   
57                          0                           0   
58                          0                           0   
59                          0                           0   
60                          0                           0   

    Imlak Varanasi Developments Private Limited  ...  \
0                                             0  ...   
1                                             0  ...   
2                                             0  ...   
3                                             0  ...   
4                                             0  ...   
..                                          ...  ...   
56                                            0  ...   
57                                            0  ...   
58                                            0  ...   
59                                            0  ...   
60                                            0  ...   

    Tata Teleservices (Maharashtra) Ltd.  Tata Teleservices Limited  \
0                           

In [44]:
data2=pd.read_excel(r"D:\IITB\econometrics project\tata_grp\data2.xlsx")
data2=data2.fillna(0)
data2

family ownership
0                0.0
1                0.0
2                0.0
3                0.0
4                0.0
..               ...
56               0.0
57               0.0
58               0.0
59               0.0
60               0.0

[61 rows x 1 columns]

In [45]:
arr1 = pd.DataFrame(data)
arr1=arr1.to_numpy()
print(arr1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [46]:
arr2 = pd.DataFrame(data2)
arr2=arr2.to_numpy()
print(arr2)

[[ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 8.77]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [19.28]
 [ 0.  ]
 [35.51]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]]


In [47]:
print(len(arr1))
print(len(arr2))

61
61


Finding control rights

In [48]:
T=input("Enter Threshold Value: ")
T=int(T)
print(T)

0


In [49]:
indexes=[]
for i in range(0,len(data.columns)):
    indexes.append(i)
og_indexes=indexes.copy()
indexes


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60]

In [50]:
def func(a,b):
    cfr=[]
    sum=0
    for i in b:
        if (i in a):
            sum=sum+arr2[i][0]
            for j in a:
                sum=sum+arr1[j][i]
            cfr.append(sum)
        else:
            cfr.append(np.nan)
        sum=0
    return cfr

In [51]:
r=func(indexes,og_indexes)

print(r)

[0.0, 75.0, 56.419999999999995, 75.0, 0.0, 62.53, 0.0, 0.0, 0.0, 0.0, 40.71, 0.0, 0.0, 0.0, 0.0, 50.069999, 71.32, 0.0, 68.86999899999999, 0.0, 0.0, 0.0, 0.0, 50.079999, 0.0, 0.0, 0.0, 34.109998, 0.0, 0.0, 0.0, 0.0, 0.0, 35.56, 114.96, 48.850001, 72.030002, 34.660001, 44.520001, 0.0, 0.0, 73.37000200000001, 55.060001, 0.0, 42.36000000000001, 37.189998, 0.0, 0.0, 72.650002, 75.910004, 34.359998, 74.340001, 0.0, 70.19000100000001, 74.949997, 52.879999, 0.0, 36.989999, 0.0, 30.289999, 0.0]


In [52]:
while(True):
    temp_pos=0

    r=func(indexes,og_indexes)
    temp=indexes.copy()

    
    for x in r:
        
            if(x<T):
                y=r.index(x,temp_pos)
                temp_pos=y+1
               
                indexes.remove(y)
    if(temp==indexes):
        break


In [53]:
res = [x + 1 for x in indexes]
print('C({}) = {}'.format(T,res))
print(r)

C(0) = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61]
[0.0, 75.0, 56.419999999999995, 75.0, 0.0, 62.53, 0.0, 0.0, 0.0, 0.0, 40.71, 0.0, 0.0, 0.0, 0.0, 50.069999, 71.32, 0.0, 68.86999899999999, 0.0, 0.0, 0.0, 0.0, 50.079999, 0.0, 0.0, 0.0, 34.109998, 0.0, 0.0, 0.0, 0.0, 0.0, 35.56, 114.96, 48.850001, 72.030002, 34.660001, 44.520001, 0.0, 0.0, 73.37000200000001, 55.060001, 0.0, 42.36000000000001, 37.189998, 0.0, 0.0, 72.650002, 75.910004, 34.359998, 74.340001, 0.0, 70.19000100000001, 74.949997, 52.879999, 0.0, 36.989999, 0.0, 30.289999, 0.0]


In [54]:
indexes=og_indexes.copy()

In [55]:
def cct(t,p,q):
    while(True):
        temp_pos=0

        r=func(p,q)
        
        temp=p.copy()
        for x in r:
            if(x<t):
                y=r.index(x,temp_pos)
                temp_pos=y+1
                p.remove(y)
        if(temp==p):
            break
    return p


Finding critical control threshold for a firm i

In [56]:
i=input("Enter the firm whose cct is to be found: ")
i=int(i)
i=i-1

In [57]:
T=0

indexes+og_indexes.copy()
while(True):
    r=cct(T,indexes,og_indexes)
    if(i in r):
        T=T+1
        indexes=og_indexes.copy()
    else:
        break
print('Critical Control Threshold for firm {} = {}'.format(i+1,T-1))

Critical Control Threshold for firm 19 = 35
